### ISSUE TITLE
Error & App Crash when attempting to open Folder View via Right-Click Context Menu

### ISSUE THREAD

**Issue by JK98062** [stax76/MediaInfo.NET#12]
Recently encountered this bug since updating from v5.3 to v7.1.

**Application Version:** v7.1.0.0
**OS:** Windows 7 SP1 x64

Application Crashes when attempting to enter Folder View via Right-Click Context Menu in v7.1. (Immediately after Clicking Folder)
Two Errors pop-up, one after the other, then the Application force closes.
These are the two errors.

1st Error:
```
FileLoadException

Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

System.IO.FileLoadException: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at MediaInfoNET.MainWindow.FolderView()
   at MediaInfoNET.MainWindow.FolderMenuItem_Click(Object sender, RoutedEventArgs e) in D:\Projekte\CS\MediaInfo.NET\src\MainWindow.xaml.cs:line 1090
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ```

![Error](https://user-images.githubusercontent.com/32981828/114671570-63f06280-9d43-11eb-9a8a-b0c5de24a984.png)

2nd Error:
```
FileLoadException

Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

System.IO.FileLoadException: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at MediaInfoNET.MainWindow.FolderView()
   at MediaInfoNET.MainWindow.FolderMenuItem_Click(Object sender, RoutedEventArgs e) in D:\Projekte\CS\MediaInfo.NET\src\MainWindow.xaml.cs:line 1090
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MediaInfoNET.Program.AppMain() in D:\Projekte\CS\MediaInfo.NET\src\Program.cs:line 32
   at MediaInfoNET.Program.Main(String[] args) in D:\Projekte\CS\MediaInfo.NET\src\Program.cs:line 20
   ```
   
![Consecutive Error](https://user-images.githubusercontent.com/32981828/114673804-bf235480-9d45-11eb-86bd-3015f6f6dbbf.png)

**Comment by stax76** [comment]
You can try to install PowerShell 5.1:

https://docs.microsoft.com/en-gb/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-windows-powershell-5-1

**Comment by JK98062** [comment]
I've attempted to Install PowerShell 5.1 on my System, but the Install fails each time.
Install fails during mandatory restart when Windows is 'Configuring Updates', it fails twice then restarts normally, and the error it gives (from the Update Log) is 80070005, which supposedly means 'Access Denied due to Insufficient Credentials', seeing as I performed the install using the appropriate Creds and that the 80070005 error is occurring prior to my User Account even being logged in, I'm not too sure what to do.
I've followed all steps mentioned in the Official Documentation and have tried searching for possible solutions to the issue, but I haven't been able to find anything helpful. (Documentation at [https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/setup/install-configure?view=powershell-7.1](url))

Any suggestions? I know it's not your responsibility to provide Support for Systems & Software that isn't yours or of your making, so all good if you cbf'd with it.

**Comment by stax76** [comment]
You can try installing this:

https://www.microsoft.com/en-us/download/details.aspx?id=54616

**Comment by JK98062** [comment]
WMF 5.1 is what I’ve been trying to install because that’s; by far; the easiest method to get PowerShell 5.1 onto Win 7.

**Comment by stax76** [comment]
The folder view feature is entirely based on powershell.

You can try to google 'powershell 80070005' and ask in forums that are specialized for windows and powershell, I'm certainly not an expert in the credential area and have only limited interest in this particular issue.

Or maybe installing Windows 10 might be an option.

**Comment by JK98062** [comment]
Windows 10 isn’t really an option unless I can find a Distribution of it with all the Silent Telemetry & other bullsh*t removed.

Does MediaInfo.NET explicitly need PowerShell 5.1 to utilise the Folder View Function or will it work with an earlier version of PowerShell?

**Comment by stax76** [comment]
I guess 5.1 is the minimum required version.

**Comment by JK98062** [comment]
Ahkk, all good mate.
I’ll close the Issue since it’s specific to my System.

Thanks for your help though, it’s much appreciated.
